logging:
  config: classpath:logback-spring-dev.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ysl13222031857
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 50
      idle-timeout: 180000

##默认密码为空
redis:
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池中的最小空闲连接
      max-idle: 10
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 100000
  timeout: 5000
  database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

animal:
  dog:
    name: "tom"
    age: 20
    play:
    - swim
    - football
    - drup
