logging:
  config: classpath:logback-spring-dev.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ysl_learn?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    data-username: root
    data-password: 'yangshilei'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 50
      idle-timeout: 180000

mybatis:
  # mapper文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

animal:
  dog:
    name: tom
    age: 20
    play:
    - swim
    - football
    - drup
